{
 "title": "Docker Hub Stats",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "capsule Pulls",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "docker_hub_image_pulls_total{image=\"capsule\"}",
     "legendFormat": "{{ image }}"
    }
   ]
  },
  {
   "title": "capsule Pulls",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(docker_hub_image_pulls_total{image=\"capsule\"})"
    }
   ]
  },
  {
   "title": "capsule Pulls Per Minute",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "rate(docker_hub_image_pulls_total{image=\"capsule\"}[1m]) * 60 "
    }
   ]
  },
  {
   "title": "capsule-proxy Pulls",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "docker_hub_image_pulls_total{image=\"capsule-proxy\"}",
     "legendFormat": "{{ image }}"
    }
   ]
  },
  {
   "title": "capsule-proxy Pulls",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(docker_hub_image_pulls_total{image=\"capsule-proxy\"})"
    }
   ]
  },
  {
   "title": "capsule-proxy Pulls Per Hour",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "rate(docker_hub_image_pulls_total{image=\"capsule-proxy\"}[1m]) * 60 "
    }
   ]
  },
  {
   "title": "kamaji Pulls",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "docker_hub_image_pulls_total{image=\"kamaji\"}",
     "legendFormat": "{{ image }}"
    }
   ]
  },
  {
   "title": "kamaji Pulls",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(docker_hub_image_pulls_total{image=\"kamaji\"})"
    }
   ]
  },
  {
   "title": "kamaji Pulls Per Hour",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "rate(docker_hub_image_pulls_total{image=\"kamaji\"}[1m]) * 60 "
    }
   ]
  }
 ]
}