## grafana_datasources.yml ##

apiVersion: 1

datasources:
  - name: 'prometheus'
    type: 'prometheus'
    access: 'proxy'
    url: 'http://prometheus:9090'

  - name: 'github'
    type: grafana-github-datasource
    #jsonData:
    #    owner: ""
    #    repository: ""
    secureJsonData:
        accessToken: "<github api token>"